### ISSUE TITLE
FR10. The application will pull/push from a database

### ISSUE THREAD

**Issue by Sarsaparilla29** [WSU-4110/Health-Productivity-App#10]
|FR10. The application will pull/push from a database|
|---|
|**Goal**:  FR10 application will be able to pull/push from a database. 
**Stakeholders:** Customers|
| **Description:**  There will be a button where users can pull and push applications from the database for their needs.  |
| **Origin:** Brainstorming with group on 2/15/2022.|
| **Version:** 1.0  |  
|**Date:** 02/18/2022 
|  **Priority:** 1 |

**Comment by masrurakif62** [comment]
The app is now able to store and utilize the information with the back-end.
