### ISSUE TITLE
FR11.  Read Computers Internal Clock

### ISSUE THREAD

**Issue by Sarsaparilla29** [WSU-4110/Health-Productivity-App#11]
|FR11.  Read Computers Internal Clock|
|---|
|**Goal**: The application will be able to read the computers internal clock.
**Stakeholders:** Users|
| **Description:** The application will read the computers internal clock in order to provide accurate and timely reminders, as well as being able to display the time on an analog display. |
| **Origin:** This is considered a necessary component in order for the system to work properly.|
| **Version:** 1.0  |  
|**Date:** 02/18/2022  
|  **Priority:** 1 |

**Comment by masrurakif62** [comment]
Application can read the computer's clock and output onto an analog clock within the application window.
