### ISSUE TITLE
FR13.  Functional Window

### ISSUE THREAD

**Issue by Sarsaparilla29** [WSU-4110/Health-Productivity-App#13]
|FR13.  Functional Window|
|---|
|**Goal**: The window will be functional and allow the user to scroll/ click on buttons
**Stakeholders:** Users|
| **Description:** The application must have a well designed functional window including buttons and the ability to scroll down reminders in order to provide a positive user experience. |
| **Origin:** Discussion on best ways to design the UI/UX |
| **Version:** 1.0  |  
|**Date:** 02/18/2022  
|  **Priority:** 3 |

**Comment by masrurakif62** [comment]
Application now has a functional window.
