### ISSUE TITLE
FR7. Create personal account with unique username and password

### ISSUE THREAD

**Issue by Sarsaparilla29** [WSU-4110/Health-Productivity-App#7]
|FR7. Create personal account with unique username and password|
|---|
|**Goal**: FR7 will allow users to create personal accounts with unique username and password.
**Stakeholders:** Customers|
| **Description:**  For using the app the user has to create a personal account with a unique username and password. The password will be 8 characters long, along with one upper case, a lowercase letter, one number, also a special symbol has to be included with the password. |
| **Origin:** Brainstorming with group on 2/15/2022.|
| **Version:** 1.0  |  
|**Date:** 02/18/2022 
|  **Priority:** 1 |

**Comment by masrurakif62** [comment]
Issue closed with Pull Request #28
