### ISSUE TITLE
FR8. Login with personal account

### ISSUE THREAD

**Issue by Sarsaparilla29** [WSU-4110/Health-Productivity-App#8]
|FR8. Login with personal account|
|---|
|**Goal**: FR8 users have to login with their personal account. 
**Stakeholders:** Customers|
| **Description:**  For using the app users have to log in with their account. If a user puts the wrong username or password three times in a row the app will automatically block the user for 30 minutes. After 30 minutes users can retry to login into their account again. |
| **Origin:** Brainstorming with group on 2/15/2022.|
| **Version:** 1.0  |  
|**Date:** 02/18/2022 
|  **Priority:** 1 |

**Comment by masrurakif62** [comment]
Issue closed with Pull Request #28
